# Generated by Django 4.0.6 on 2022-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Refresco', models.CharField(max_length=40)),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('CONT', models.FloatField()),
            ],
        ),
    ]
